# TCL File Generated by Component Editor 17.0
# Sat Feb 24 21:36:41 MST 2018
# DO NOT MODIFY


# 
# hallSensorDetector "hallSensorDetector" v1.0
#  2018.02.24.21:36:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hallSensorDetector
# 
set_module_property DESCRIPTION ""
set_module_property NAME hallSensorDetector
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hallSensorDetector
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hall_sensor_comparator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hall_sensor_comparator.vhd VHDL PATH HallSensors/hall_sensor_comparator.vhd TOP_LEVEL_FILE
add_fileset_file hall_debouncer.vhd VHDL PATH HallSensors/hall_debouncer.vhd
add_fileset_file hall_sensor_accumulator.vhd VHDL PATH HallSensors/hall_sensor_accumulator.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point systemClock
# 
add_interface systemClock clock end
set_interface_property systemClock clockRate 0
set_interface_property systemClock ENABLED true
set_interface_property systemClock EXPORT_OF ""
set_interface_property systemClock PORT_NAME_MAP ""
set_interface_property systemClock CMSIS_SVD_VARIABLES ""
set_interface_property systemClock SVD_ADDRESS_GROUP ""

add_interface_port systemClock sysClk clk Input 1


# 
# connection point samplingFullFreqClock
# 
add_interface samplingFullFreqClock clock end
set_interface_property samplingFullFreqClock clockRate 0
set_interface_property samplingFullFreqClock ENABLED true
set_interface_property samplingFullFreqClock EXPORT_OF ""
set_interface_property samplingFullFreqClock PORT_NAME_MAP ""
set_interface_property samplingFullFreqClock CMSIS_SVD_VARIABLES ""
set_interface_property samplingFullFreqClock SVD_ADDRESS_GROUP ""

add_interface_port samplingFullFreqClock fullClk clk Input 1


# 
# connection point samplingHalfFreqClock
# 
add_interface samplingHalfFreqClock clock end
set_interface_property samplingHalfFreqClock clockRate 0
set_interface_property samplingHalfFreqClock ENABLED true
set_interface_property samplingHalfFreqClock EXPORT_OF ""
set_interface_property samplingHalfFreqClock PORT_NAME_MAP ""
set_interface_property samplingHalfFreqClock CMSIS_SVD_VARIABLES ""
set_interface_property samplingHalfFreqClock SVD_ADDRESS_GROUP ""

add_interface_port samplingHalfFreqClock halfClk clk Input 1


# 
# connection point systemReset
# 
add_interface systemReset reset end
set_interface_property systemReset associatedClock systemClock
set_interface_property systemReset synchronousEdges DEASSERT
set_interface_property systemReset ENABLED true
set_interface_property systemReset EXPORT_OF ""
set_interface_property systemReset PORT_NAME_MAP ""
set_interface_property systemReset CMSIS_SVD_VARIABLES ""
set_interface_property systemReset SVD_ADDRESS_GROUP ""

add_interface_port systemReset reset reset Input 1


# 
# connection point frontLeftHall
# 
add_interface frontLeftHall conduit end
set_interface_property frontLeftHall associatedClock systemClock
set_interface_property frontLeftHall associatedReset ""
set_interface_property frontLeftHall ENABLED true
set_interface_property frontLeftHall EXPORT_OF ""
set_interface_property frontLeftHall PORT_NAME_MAP ""
set_interface_property frontLeftHall CMSIS_SVD_VARIABLES ""
set_interface_property frontLeftHall SVD_ADDRESS_GROUP ""

add_interface_port frontLeftHall frontLeft import Input 1


# 
# connection point rearRightHall
# 
add_interface rearRightHall conduit end
set_interface_property rearRightHall associatedClock systemClock
set_interface_property rearRightHall associatedReset ""
set_interface_property rearRightHall ENABLED true
set_interface_property rearRightHall EXPORT_OF ""
set_interface_property rearRightHall PORT_NAME_MAP ""
set_interface_property rearRightHall CMSIS_SVD_VARIABLES ""
set_interface_property rearRightHall SVD_ADDRESS_GROUP ""

add_interface_port rearRightHall rearRight import Input 1


# 
# connection point rearLeftHall_1
# 
add_interface rearLeftHall_1 conduit end
set_interface_property rearLeftHall_1 associatedClock systemClock
set_interface_property rearLeftHall_1 associatedReset ""
set_interface_property rearLeftHall_1 ENABLED true
set_interface_property rearLeftHall_1 EXPORT_OF ""
set_interface_property rearLeftHall_1 PORT_NAME_MAP ""
set_interface_property rearLeftHall_1 CMSIS_SVD_VARIABLES ""
set_interface_property rearLeftHall_1 SVD_ADDRESS_GROUP ""

add_interface_port rearLeftHall_1 rearLeft import Input 1


# 
# connection point frontRightHall
# 
add_interface frontRightHall conduit end
set_interface_property frontRightHall associatedClock systemClock
set_interface_property frontRightHall associatedReset ""
set_interface_property frontRightHall ENABLED true
set_interface_property frontRightHall EXPORT_OF ""
set_interface_property frontRightHall PORT_NAME_MAP ""
set_interface_property frontRightHall CMSIS_SVD_VARIABLES ""
set_interface_property frontRightHall SVD_ADDRESS_GROUP ""

add_interface_port frontRightHall frontRight import Input 1


# 
# connection point front
# 
add_interface front avalon end
set_interface_property front addressUnits WORDS
set_interface_property front associatedClock systemClock
set_interface_property front associatedReset systemReset
set_interface_property front bitsPerSymbol 8
set_interface_property front burstOnBurstBoundariesOnly false
set_interface_property front burstcountUnits WORDS
set_interface_property front explicitAddressSpan 0
set_interface_property front holdTime 0
set_interface_property front linewrapBursts false
set_interface_property front maximumPendingReadTransactions 0
set_interface_property front maximumPendingWriteTransactions 0
set_interface_property front readLatency 0
set_interface_property front readWaitTime 1
set_interface_property front setupTime 0
set_interface_property front timingUnits Cycles
set_interface_property front writeWaitTime 0
set_interface_property front ENABLED true
set_interface_property front EXPORT_OF ""
set_interface_property front PORT_NAME_MAP ""
set_interface_property front CMSIS_SVD_VARIABLES ""
set_interface_property front SVD_ADDRESS_GROUP ""

add_interface_port front readFront read Input 1
add_interface_port front frontRatio readdata Output 32
set_interface_assignment front embeddedsw.configuration.isFlash 0
set_interface_assignment front embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment front embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment front embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rear
# 
add_interface rear avalon end
set_interface_property rear addressUnits WORDS
set_interface_property rear associatedClock systemClock
set_interface_property rear associatedReset systemReset
set_interface_property rear bitsPerSymbol 8
set_interface_property rear burstOnBurstBoundariesOnly false
set_interface_property rear burstcountUnits WORDS
set_interface_property rear explicitAddressSpan 0
set_interface_property rear holdTime 0
set_interface_property rear linewrapBursts false
set_interface_property rear maximumPendingReadTransactions 0
set_interface_property rear maximumPendingWriteTransactions 0
set_interface_property rear readLatency 0
set_interface_property rear readWaitTime 1
set_interface_property rear setupTime 0
set_interface_property rear timingUnits Cycles
set_interface_property rear writeWaitTime 0
set_interface_property rear ENABLED true
set_interface_property rear EXPORT_OF ""
set_interface_property rear PORT_NAME_MAP ""
set_interface_property rear CMSIS_SVD_VARIABLES ""
set_interface_property rear SVD_ADDRESS_GROUP ""

add_interface_port rear rearRatio readdata Output 32
add_interface_port rear readRear read Input 1
set_interface_assignment rear embeddedsw.configuration.isFlash 0
set_interface_assignment rear embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment rear embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment rear embeddedsw.configuration.isPrintableDevice 0


# 
# connection point whole
# 
add_interface whole avalon end
set_interface_property whole addressUnits WORDS
set_interface_property whole associatedClock systemClock
set_interface_property whole associatedReset systemReset
set_interface_property whole bitsPerSymbol 8
set_interface_property whole burstOnBurstBoundariesOnly false
set_interface_property whole burstcountUnits WORDS
set_interface_property whole explicitAddressSpan 0
set_interface_property whole holdTime 0
set_interface_property whole linewrapBursts false
set_interface_property whole maximumPendingReadTransactions 0
set_interface_property whole maximumPendingWriteTransactions 0
set_interface_property whole readLatency 0
set_interface_property whole readWaitTime 1
set_interface_property whole setupTime 0
set_interface_property whole timingUnits Cycles
set_interface_property whole writeWaitTime 0
set_interface_property whole ENABLED true
set_interface_property whole EXPORT_OF ""
set_interface_property whole PORT_NAME_MAP ""
set_interface_property whole CMSIS_SVD_VARIABLES ""
set_interface_property whole SVD_ADDRESS_GROUP ""

add_interface_port whole frontRearRatio readdata Output 32
add_interface_port whole readWhole read Input 1
set_interface_assignment whole embeddedsw.configuration.isFlash 0
set_interface_assignment whole embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment whole embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment whole embeddedsw.configuration.isPrintableDevice 0


# 
# connection point newDataInterrupt
# 
add_interface newDataInterrupt interrupt end
set_interface_property newDataInterrupt associatedAddressablePoint ""
set_interface_property newDataInterrupt associatedClock systemClock
set_interface_property newDataInterrupt associatedReset systemReset
set_interface_property newDataInterrupt bridgedReceiverOffset ""
set_interface_property newDataInterrupt bridgesToReceiver ""
set_interface_property newDataInterrupt ENABLED true
set_interface_property newDataInterrupt EXPORT_OF ""
set_interface_property newDataInterrupt PORT_NAME_MAP ""
set_interface_property newDataInterrupt CMSIS_SVD_VARIABLES ""
set_interface_property newDataInterrupt SVD_ADDRESS_GROUP ""

add_interface_port newDataInterrupt raiseInterrupt irq Output 1


# 
# connection point samplingImpulse
# 
add_interface samplingImpulse clock end
set_interface_property samplingImpulse clockRate 0
set_interface_property samplingImpulse ENABLED true
set_interface_property samplingImpulse EXPORT_OF ""
set_interface_property samplingImpulse PORT_NAME_MAP ""
set_interface_property samplingImpulse CMSIS_SVD_VARIABLES ""
set_interface_property samplingImpulse SVD_ADDRESS_GROUP ""

add_interface_port samplingImpulse sampleImpulse clk Input 1

