# TCL File Generated by Component Editor 17.0
# Wed Mar 07 14:36:33 MST 2018
# DO NOT MODIFY


# 
# pwmBrushed "pwmBrushed" v1.1
#  2018.03.07.14:36:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwmBrushed
# 
set_module_property DESCRIPTION ""
set_module_property NAME pwmBrushed
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pwmBrushed
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm.vhdl VHDL PATH PWMGeneration/pwm.vhdl TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter sys_clk INTEGER 50000000
set_parameter_property sys_clk DEFAULT_VALUE 50000000
set_parameter_property sys_clk DISPLAY_NAME sys_clk
set_parameter_property sys_clk TYPE INTEGER
set_parameter_property sys_clk UNITS None
set_parameter_property sys_clk ALLOWED_RANGES -2147483648:2147483647
set_parameter_property sys_clk HDL_PARAMETER true
add_parameter pwm_freq INTEGER 50000
set_parameter_property pwm_freq DEFAULT_VALUE 50000
set_parameter_property pwm_freq DISPLAY_NAME pwm_freq
set_parameter_property pwm_freq TYPE INTEGER
set_parameter_property pwm_freq UNITS None
set_parameter_property pwm_freq ALLOWED_RANGES -2147483648:2147483647
set_parameter_property pwm_freq HDL_PARAMETER true
add_parameter bits_resolution INTEGER 8
set_parameter_property bits_resolution DEFAULT_VALUE 8
set_parameter_property bits_resolution DISPLAY_NAME bits_resolution
set_parameter_property bits_resolution TYPE INTEGER
set_parameter_property bits_resolution UNITS None
set_parameter_property bits_resolution ALLOWED_RANGES -2147483648:2147483647
set_parameter_property bits_resolution HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_slave_write_n write_n Input 1
add_interface_port avalon_slave avalon_slave_writedata writedata Input 8
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Direction1
# 
add_interface Direction1 conduit end
set_interface_property Direction1 associatedClock clock
set_interface_property Direction1 associatedReset reset
set_interface_property Direction1 ENABLED true
set_interface_property Direction1 EXPORT_OF ""
set_interface_property Direction1 PORT_NAME_MAP ""
set_interface_property Direction1 CMSIS_SVD_VARIABLES ""
set_interface_property Direction1 SVD_ADDRESS_GROUP ""

add_interface_port Direction1 dir_1 export Output 1


# 
# connection point Direction2
# 
add_interface Direction2 conduit end
set_interface_property Direction2 associatedClock clock
set_interface_property Direction2 associatedReset ""
set_interface_property Direction2 ENABLED true
set_interface_property Direction2 EXPORT_OF ""
set_interface_property Direction2 PORT_NAME_MAP ""
set_interface_property Direction2 CMSIS_SVD_VARIABLES ""
set_interface_property Direction2 SVD_ADDRESS_GROUP ""

add_interface_port Direction2 dir_2 export Output 1


# 
# connection point PulseWidthModulatedSignal
# 
add_interface PulseWidthModulatedSignal conduit end
set_interface_property PulseWidthModulatedSignal associatedClock clock
set_interface_property PulseWidthModulatedSignal associatedReset ""
set_interface_property PulseWidthModulatedSignal ENABLED true
set_interface_property PulseWidthModulatedSignal EXPORT_OF ""
set_interface_property PulseWidthModulatedSignal PORT_NAME_MAP ""
set_interface_property PulseWidthModulatedSignal CMSIS_SVD_VARIABLES ""
set_interface_property PulseWidthModulatedSignal SVD_ADDRESS_GROUP ""

add_interface_port PulseWidthModulatedSignal pwm_signal export Output 1

