# TCL File Generated by Component Editor 17.0
# Sat Feb 24 21:35:01 MST 2018
# DO NOT MODIFY


# 
# samplingClock "samplingClock" v1.0
#  2018.02.24.21:35:01
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module samplingClock
# 
set_module_property DESCRIPTION ""
set_module_property NAME samplingClock
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME samplingClock
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL samplingClock
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file samplingClock.vhd VHDL PATH HallSensors/samplingClock.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point systemClock
# 
add_interface systemClock clock end
set_interface_property systemClock clockRate 0
set_interface_property systemClock ENABLED true
set_interface_property systemClock EXPORT_OF ""
set_interface_property systemClock PORT_NAME_MAP ""
set_interface_property systemClock CMSIS_SVD_VARIABLES ""
set_interface_property systemClock SVD_ADDRESS_GROUP ""

add_interface_port systemClock clock_sink_1_clk clk Input 1


# 
# connection point normalPeriod
# 
add_interface normalPeriod clock start
set_interface_property normalPeriod associatedDirectClock ""
set_interface_property normalPeriod clockRate 0
set_interface_property normalPeriod clockRateKnown false
set_interface_property normalPeriod ENABLED true
set_interface_property normalPeriod EXPORT_OF ""
set_interface_property normalPeriod PORT_NAME_MAP ""
set_interface_property normalPeriod CMSIS_SVD_VARIABLES ""
set_interface_property normalPeriod SVD_ADDRESS_GROUP ""

add_interface_port normalPeriod normal_freq_new_signal clk Output 1


# 
# connection point halfPeriod
# 
add_interface halfPeriod clock start
set_interface_property halfPeriod associatedDirectClock ""
set_interface_property halfPeriod clockRate 0
set_interface_property halfPeriod clockRateKnown false
set_interface_property halfPeriod ENABLED true
set_interface_property halfPeriod EXPORT_OF ""
set_interface_property halfPeriod PORT_NAME_MAP ""
set_interface_property halfPeriod CMSIS_SVD_VARIABLES ""
set_interface_property halfPeriod SVD_ADDRESS_GROUP ""

add_interface_port halfPeriod double_freq_new_signal clk Output 1


# 
# connection point impulse
# 
add_interface impulse clock start
set_interface_property impulse associatedDirectClock ""
set_interface_property impulse clockRate 0
set_interface_property impulse clockRateKnown false
set_interface_property impulse ENABLED true
set_interface_property impulse EXPORT_OF ""
set_interface_property impulse PORT_NAME_MAP ""
set_interface_property impulse CMSIS_SVD_VARIABLES ""
set_interface_property impulse SVD_ADDRESS_GROUP ""

add_interface_port impulse sample_impulse_signal clk Output 1

