# TCL File Generated by Component Editor 17.0
# Sat Feb 24 23:17:22 MST 2018
# DO NOT MODIFY


# 
# ultraSonicRangeFinder "ultraSonicRangeFinder" v1.0
#  2018.02.24.23:17:22
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ultraSonicRangeFinder
# 
set_module_property DESCRIPTION ""
set_module_property NAME ultraSonicRangeFinder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ultraSonicRangeFinder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL proximity
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file proximity.vhd VHDL PATH UltraSonicRangeFinder/proximity.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter sys_clk INTEGER 50000000
set_parameter_property sys_clk DEFAULT_VALUE 50000000
set_parameter_property sys_clk DISPLAY_NAME sys_clk
set_parameter_property sys_clk TYPE INTEGER
set_parameter_property sys_clk UNITS None
set_parameter_property sys_clk HDL_PARAMETER true
add_parameter cycle_time INTEGER 49
set_parameter_property cycle_time DEFAULT_VALUE 49
set_parameter_property cycle_time DISPLAY_NAME cycle_time
set_parameter_property cycle_time TYPE INTEGER
set_parameter_property cycle_time UNITS None
set_parameter_property cycle_time HDL_PARAMETER true
add_parameter time_per_inch INTEGER 147
set_parameter_property time_per_inch DEFAULT_VALUE 147
set_parameter_property time_per_inch DISPLAY_NAME time_per_inch
set_parameter_property time_per_inch TYPE INTEGER
set_parameter_property time_per_inch UNITS None
set_parameter_property time_per_inch HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point rangeValue
# 
add_interface rangeValue avalon end
set_interface_property rangeValue addressUnits WORDS
set_interface_property rangeValue associatedClock clock
set_interface_property rangeValue associatedReset reset
set_interface_property rangeValue bitsPerSymbol 8
set_interface_property rangeValue burstOnBurstBoundariesOnly false
set_interface_property rangeValue burstcountUnits WORDS
set_interface_property rangeValue explicitAddressSpan 0
set_interface_property rangeValue holdTime 0
set_interface_property rangeValue linewrapBursts false
set_interface_property rangeValue maximumPendingReadTransactions 0
set_interface_property rangeValue maximumPendingWriteTransactions 0
set_interface_property rangeValue readLatency 0
set_interface_property rangeValue readWaitTime 1
set_interface_property rangeValue setupTime 0
set_interface_property rangeValue timingUnits Cycles
set_interface_property rangeValue writeWaitTime 0
set_interface_property rangeValue ENABLED true
set_interface_property rangeValue EXPORT_OF ""
set_interface_property rangeValue PORT_NAME_MAP ""
set_interface_property rangeValue CMSIS_SVD_VARIABLES ""
set_interface_property rangeValue SVD_ADDRESS_GROUP ""

add_interface_port rangeValue avalon_slave_read_n read Input 1
add_interface_port rangeValue proximity_inches_avalon_readdata readdata Output 32
set_interface_assignment rangeValue embeddedsw.configuration.isFlash 0
set_interface_assignment rangeValue embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment rangeValue embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment rangeValue embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sonarIn
# 
add_interface sonarIn conduit end
set_interface_property sonarIn associatedClock clock
set_interface_property sonarIn associatedReset ""
set_interface_property sonarIn ENABLED true
set_interface_property sonarIn EXPORT_OF ""
set_interface_property sonarIn PORT_NAME_MAP ""
set_interface_property sonarIn CMSIS_SVD_VARIABLES ""
set_interface_property sonarIn SVD_ADDRESS_GROUP ""

add_interface_port sonarIn pw_signal import Input 1

